apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: todos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: ikhripunov/simple-backend:latest
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /get-todos
            port: 3001
