apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: todos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: ikhripunov/simple-frontend:latest
        ports:
        - containerPort: 3000
