apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todos
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: master
  type: LoadBalancer
